
# Settings for hardware servers
server:
  battery:
    device_type: TCP
    slave_id: 1
    ipaddr: localhost
    ipport: 8080
    SOCaddr: 19
    poweraddr: 3
  solar:
    device_type: TCP
    slave_id: 1
    ipaddr: localhost
    ipport: 8081
    poweraddr: 0
  house:
    device_type: TCP
    slave_id: 1
    ipaddr: localhost
    ipport: 8082
    poweraddr: 0

# Settings publishing and subscribing
ZeroMQ:
  use_event_pub: yes
  battery_pub_time: 0.1
  solar_pub_time: 0.1
  house_pub_time: 0.1
  battery_SOC_port: 8090
  battery_power_port: 8093
  solar_port: 8091
  house_port: 8092
  battery_SOC_topic: 0
  battery_power_topic: 0
  solar_topic: 0
  house_topic: 0

# Physical battery characteristics
battery:
  max_capacity: 15 # kWh
  DOD_limit: 0
  charging_power_limit: 5.0
  discharging_power_limit: -5.0
  charging_efficiency: 1
  discharging_efficiency: 1
  throughput_cost: 0.018
  initial_SOC: 0

# Simulation specific settings
simulation:
  data_file_name: random_data_set.csv
  solar_row_name: asolarp
  house_row_name: aloadp
  time_step: 5 # minutes
  use_real_time: no
  use_visualisation: yes
  display_grid: yes
  display_SOC: yes
  grid_ref: 0
  control_dir: Both

# Control system settings
control:
  control_time_step: 5 # minutes
  optimiser_time_step: 20 # minutes
  data_time_step: 5 # minutes
  solar_filtering: yes
  solar_cov: 0.4
  house_filtering: yes
  house_cov: 0.4
  battery_filtering: no
  bat_cov: 0.05
  optimiser: no
  pv_self_cons: yes
  power_covariance: 0.5
  initial_optimiser_prediction: yes
  data_file_name: one_day_export.csv
  solar_row_name: asolarp
  house_row_name: aloadp
  objective: FEP # Valid Objectives: Financial, Energy, Peak, FEP, QuantisedPeak, Dispatch

# Tariff pricing settings
tariff:
  use_fixed_rate: yes
  fixed_rate: 0.27 # $/kWh
  peak_rate: 0.45 # $/kWh
  shoulder_rate: 0.35 # $/kWh
  off_peak_rate: 0.15 # $/kWh
  feed_in: 0.09 # $/kWh
  off_peak_time_morn: 7 # hours (default = 7)
  shoulder_time_morn: 7 # hours (default = 7)
  peak_time: 6 # hours (default = 6)
  shoulder_time_eve: 2 # hours (default = 2)
  off_peak_time_eve: 2 # hours (default = 2)